#cloud-config
hostname: "apps"
users:
    - name: "jarjar"
      passwd: "$1$o4wTm.HT$TyzV9aftAuUrQ9snvV5cA."
      groups:
        - "sudo"
        - "docker"           
coreos:
    units:
      - name: docker.service
        command: start
      - name: mixit-api.service
        command: start
        content: |
          [Unit]
          Description=Api mixit
          After=docker.service
          [Service]
          Restart=always
          ExecStartPre=-/usr/bin/docker kill mixit-api
          ExecStartPre=-/usr/bin/docker rm mixit-api
          ExecStartPre=/usr/bin/docker pull ymatagne/mixit-api:latest
          ExecStart=/usr/bin/docker run --name mixit-api -p 0.0.0.0:8080:8080 ymatagne/mixit-api:latest
          ExecStop=/usr/bin/docker stop mixit-api 
      - name: mixit.service
        command: start
        content: |
          [Unit]
          Description=MixIt
          After=docker.service
          [Service]
          Restart=always
          ExecStartPre=-/usr/bin/docker kill mixit-front
          ExecStartPre=-/usr/bin/docker rm mixit-front
          ExecStartPre=/usr/bin/docker pull ymatagne/mixit-front:latest
          ExecStart=/usr/bin/docker run --name mixit-front -p 0.0.0.0:80:80 ymatagne/mixit-front:latest
          ExecStop=/usr/bin/docker stop mixit-front 
